name: Continuous Delivery
on:
  push:
    branches: [ "main" ]
env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 375661828785.dkr.ecr.us-east-1.amazonaws.com/ericbrosch
  ECR_REPOSITORY: simple-flask-app
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Show image destination
      env:
        ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
      run: |
        echo "ECR registry: $ECR_REGISTRY"
        echo "ECR repository: $ECR_REPOSITORY"
        echo "Image: $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA}"
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -f simple-flask-app/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG simple-flask-app
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Debug build output
      run: |
            echo "Needs: ${{ toJSON(needs) }}"
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Terraform Init
      run: terraform -chdir=terraform init
    - name: Terraform Apply
      env:
        IMAGE_IDENTIFIER: ${{ needs.build-and-push.outputs.image }}
      run: |
        echo "Deploying image: $IMAGE_IDENTIFIER"
        terraform -chdir=terraform apply -auto-approve \
          -var="ecr_image_identifier=$IMAGE_IDENTIFIER"